# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diary.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(897, 359)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 50, 878, 227))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.task_list = QtWidgets.QGroupBox(self.layoutWidget)
        self.task_list.setObjectName("task_list")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.task_list)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list_tasks = QtWidgets.QListWidget(self.task_list)
        self.list_tasks.setObjectName("list_tasks")
        self.horizontalLayout.addWidget(self.list_tasks)
        self.gridLayout.addWidget(self.task_list, 0, 0, 1, 1)
        self.description_of_task = QtWidgets.QGroupBox(self.layoutWidget)
        self.description_of_task.setObjectName("description_of_task")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.description_of_task)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.description_of_task)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.description_of_task)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_2.addWidget(self.calendarWidget)
        self.gridLayout.addWidget(self.description_of_task, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(15, 291, 861, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.timeEdit = QtWidgets.QTimeEdit(self.layoutWidget1)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_3.addWidget(self.timeEdit)
        self.add_task = QtWidgets.QPushButton(self.layoutWidget1)
        self.add_task.setObjectName("add_task")
        self.horizontalLayout_3.addWidget(self.add_task)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.task_list.setTitle(_translate("MainWindow", "Список задач"))
        self.description_of_task.setTitle(_translate("MainWindow", "Описание задачи"))
        self.add_task.setText(_translate("MainWindow", "Добавить задачу"))
