# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 344)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.procedures = QtWidgets.QComboBox(self.centralwidget)
        self.procedures.setGeometry(QtCore.QRect(141, 51, 131, 20))
        self.procedures.setObjectName("procedures")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(141, 24, 161, 20))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(52, 22, 23, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(52, 48, 56, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(274, 50, 31, 23))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 81, 251, 241))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.description_procedure = QtWidgets.QPlainTextEdit(self.widget)
        self.description_procedure.setObjectName("description_procedure")
        self.gridLayout.addWidget(self.description_procedure, 0, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.widget)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 1, 0, 1, 1)
        self.check_register = QtWidgets.QPushButton(self.widget)
        self.check_register.setObjectName("check_register")
        self.gridLayout.addWidget(self.check_register, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ФИО"))
        self.label_2.setText(_translate("MainWindow", "Процедура"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.save_button.setText(_translate("MainWindow", "Сохранить"))
        self.check_register.setText(_translate("MainWindow", "Посмотреть свои записи"))
