# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project\my_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_my_register(object):
    def setupUi(self, my_register):
        my_register.setObjectName("my_register")
        my_register.resize(691, 310)
        self.calendarWidget = QtWidgets.QCalendarWidget(my_register)
        self.calendarWidget.setGeometry(QtCore.QRect(340, 50, 331, 221))
        self.calendarWidget.setObjectName("calendarWidget")
        self.layoutWidget = QtWidgets.QWidget(my_register)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 291, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.name_r = QtWidgets.QLineEdit(self.layoutWidget)
        self.name_r.setObjectName("name_r")
        self.gridLayout.addWidget(self.name_r, 0, 1, 1, 1)
        self.okbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.okbutton.setObjectName("okbutton")
        self.gridLayout.addWidget(self.okbutton, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 0, 1, 3)

        self.retranslateUi(my_register)
        QtCore.QMetaObject.connectSlotsByName(my_register)

    def retranslateUi(self, my_register):
        _translate = QtCore.QCoreApplication.translate
        my_register.setWindowTitle(_translate("my_register", "Form"))
        self.okbutton.setText(_translate("my_register", "OK"))
        self.label.setText(_translate("my_register", "ФИО"))
