# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project\choose_salon.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choose_salon(object):
    def setupUi(self, choose_salon):
        choose_salon.setObjectName("choose_salon")
        choose_salon.resize(256, 184)
        self.choose_sal = QtWidgets.QComboBox(choose_salon)
        self.choose_sal.setGeometry(QtCore.QRect(54, 9, 151, 20))
        self.choose_sal.setObjectName("choose_sal")
        self.label_2 = QtWidgets.QLabel(choose_salon)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 31, 16))
        self.label_2.setObjectName("label_2")
        self.layoutWidget = QtWidgets.QWidget(choose_salon)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 231, 70))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save_register = QtWidgets.QPushButton(self.layoutWidget)
        self.save_register.setObjectName("save_register")
        self.gridLayout.addWidget(self.save_register, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.layoutWidget)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(choose_salon)
        self.pushButton.setGeometry(QtCore.QRect(210, 9, 31, 21))
        self.pushButton.setObjectName("pushButton")
        self.description_salon = QtWidgets.QPlainTextEdit(choose_salon)
        self.description_salon.setGeometry(QtCore.QRect(10, 40, 231, 41))
        self.description_salon.setObjectName("description_salon")

        self.retranslateUi(choose_salon)
        QtCore.QMetaObject.connectSlotsByName(choose_salon)

    def retranslateUi(self, choose_salon):
        _translate = QtCore.QCoreApplication.translate
        choose_salon.setWindowTitle(_translate("choose_salon", "Form"))
        self.label_2.setText(_translate("choose_salon", "Салон"))
        self.save_register.setText(_translate("choose_salon", "Записаться"))
        self.label.setText(_translate("choose_salon", "                Выберите удобное вам время"))
        self.pushButton.setText(_translate("choose_salon", "OK"))
